export { default as cycleWonder } from "./Cycle-unblur-wonder-3.png";
export { default as earthHeritage1 } from "./EarthHeritageiamge1.png";
export { default as eveningWalk } from "./Evening Walk-unblur-wonder-3.png";
export { default as page1 } from "./Page 1 -unblur.png";
export { default as page2 } from "./Page 2-wonder-3.png";
export { default as page3 } from "./Page 3 -unblur.png";
export { default as page4b } from "./Page 4 b.jpeg";
export { default as page4 } from "./Page 4)-unblur.png";
export { default as page5b } from "./Page 5 b.jpeg";
export { default as page5cWonder } from "./Page 5 c-unblur-wonder-3.png";
export { default as page5d } from "./Page 5 d-unblur.png";
export { default as page5e } from "./Page 5 e-unblur.png";
export { default as trekWonder } from "./Treck-wonder-3.png";
export { default as heritageSuite } from "./heritage_earth_suite_1779811380883.png";
export { default as malnadSecond } from "./malnadsecondimage.png";
export { default as newImage } from "./new.png";
export { default as diningImage } from "./dining_experience.png";
export { default as dining1 } from "./dining_1.png";
export { default as dining2 } from "./dining_2.png";
export { default as dining3 } from "./dining_3.png";
export { default as poolImage } from "./pool.png";
export { default as eveningWalk2 } from "./Evening Walk 2-unblur-wonder-3.png";
export { default as trekCheckDam2 } from "./Treck Check Dam 2-unblur-wonder-3.png";
